resources:
  - name: git-demo-slices-repo
    type: git
    source:
      uri: git@github.com:Alvtag/slices
      branch: master
      private_key: ((github-private-key))
jobs:
  - name: test-demo-slices

    plan:

      - get: git-demo-slices-repo
        trigger: true
      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: runmymind/docker-android-sdk
              tag: "ubuntu-standalone"
          run:
            path: sh
            args:
            - -exc
            - |
              cd git-demo-slices-repo
              ./gradlew testDebugUnitTest
          inputs:
          - name: git-demo-slices-repo